# Generated by Django 3.1.7 on 2021-05-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
